### ISSUE TITLE
Flytte fra internal til public repo

### ISSUE THREAD

**Issue by MikAoJk** [navikt/sendsoknad-boot#94]
Hei!
Lurte på om det var noe spesiell grunn til at repoet er internal.
https://github.com/navikt/offentlig

**Comment by sjoblomjsqueed** [comment]
Jeg har nå gått ignenom alle 11-siffrige nummer i kodebasen og fjernet det fnr til en ekte person som kommit in. Git-historikken [er omskriven](https://github.com/navikt/offentlig/blob/master/guider/sikkerhetsvask.md#skrive-om-git-historikk).

Jeg åpner nå repoet. \o/

**Comment by MikAoJk** [comment]
Godt jobbet! :100:
